spring:
  profiles:
    active: test

  thymeleaf:
    cache: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 2MB

server:
  servlet:
    context-path: /

upload:
  profile-path: "/upload/profile/"